version: '3.8'

services:
  datalake:
    image: minio/minio:RELEASE.2025-02-03T21-03-04Z-cpuv1
    volumes:
      - minio_data:/data
    networks:
      - datalakehouse
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: minio server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: on-failure

  minio-client:
    image: minio/mc
    depends_on:
      - datalake
    networks:
      - datalakehouse
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./clientes.csv:/clientes.csv
      - ./upload-csv.sh:/upload-csv.sh
    entrypoint: sh /upload-csv.sh

volumes:
  minio_data:

networks:
  datalakehouse:
    driver: bridge