version: '3.8'

# This Docker Compose file sets up the MinIO Data Lake service.
#
# To run:
#   1. Create a .env file based on .env.example
#   2. Run 'docker-compose up -d'
#
# The MinIO UI will be available at http://localhost:9001

services:
  datalake:
    image: minio/minio:RELEASE.2025-02-03T21-03-04Z-cpuv1
    volumes:
      - minio_data:/data
    networks:
      - datalakehouse
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: on-failure

volumes:
  minio_data:
    driver: local

networks:
  datalakehouse:
    driver: bridge